version: '3.7'
services:
  myapp:
    container_name: myapp
    image: ensf400-lab4:latest
    build: .
    ports: 
      - "8080:8080"
    volumes:
    - "app_data:/var/app_data"

volumes:
  app_data: