version: '3.8'
services:

  # Building and testing environment
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/denoslab/toolbox:testing
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    environment:
      - TESTVAR=${TESTVAR:-app}
    volumes:
    
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
