services:
  app:
    container_name: myapp
    image: ghcr.io/NaderNab/toolbox:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TESTVAR=${TESTVAR:-/src}
    volumes:
      - ./app_data:/var/app_data
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
