version: '3.8'
services:

  # Building and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:/src}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
    - ${HOME}/.gitconfig:/home/ubuntu/.gitconfig
    - ${HOME}/.ssh:/home/ubuntu/.ssh
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

  # Example container with DooD and host file/net access
  app1:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:/src}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - toolbox_data:/data  # Added persistent storage volume
    ports:
      - "8081:80"  # Changed from network_mode to port mapping

  # Example of running the same image with different intent
  app2:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:/src}
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    ports:
      - "8082:80"  # Expose a different port for app2

volumes:
  toolbox_data:
