services:

  # Building and testing environment
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:latest
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - /Users/austinkim/ENSF400/toolbox
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
