
services:

  # Building and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:latest
    
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
    - ${HOME}/.gitconfig:/home/ubuntu/.gitconfig
    - ${HOME}/.ssh:/home/ubuntu/.ssh
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
    platform: linux/amd64
    network_mode: "host"

  # Example container with DooD and host file/net access
  app1:
    image: ghcr.io/growlf/toolbox:latest
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    platform: linux/amd64
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    
    
  # Example of running the same image with different intent
  app2:
    image: ghcr.io/growlf/toolbox:latest
    stdin_open: true
    platform: linux/amd64
    tty: true
    command: ["/bin/bash"]

    
