version: '3.8'

services:
  toolbox-app:
    image: my-toolbox-image  # Replace with the actual image name
    container_name: toolbox-container
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - ./data:/app/data  
    environment:
      - ENV=development

