
services:
  toolbox-app:
    image: your-dockerhub-username/toolbox:your-branch-name
    container_name: toolbox-app
    restart: unless-stopped
    volumes:
      - ./your-local-folder:/app  # Adjust this to your local directory
    ports:
      - "8080:80"                # Change ports if needed
    environment:
      - ENV_VAR=production       # Add any environment variables
    networks:
      - toolbox-net

networks:
  toolbox-net:
    driver: bridge
