version: '3.8'
services:
  app:
    image: ghcr.io/growlf/toolbox:testing
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - ./local-folder:/workspace  # Adjust this to your local directory
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
